---
apiVersion: v1
kind: Namespace
metadata:
  name: spark
  labels:
    app: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-serviceaccount
  namespace: spark
  labels:
    app: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-driver-role
  namespace: spark
  labels:
    app: spark
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - create
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver
  namespace: spark
  labels:
    app: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-driver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: spark-serviceaccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-driver-controller
  labels:
    app: spark
    component: spark-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-driver
  template:
    metadata:
      labels:
        app: spark
        component: spark-driver
    spec:
      containers:
      - name: spark-driver
        image: k8s.gcr.io/spark:1.5.2_v1
        command: ["/start-master"]
        ports:
        - containerPort: 7077
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-driver-service
  labels:
    app: spark
    component: spark-driver
spec:
  ports:
  - port: 7077
    targetPort: 7077
    name: spark
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    component: spark-driver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: spark-driver-ui-proxy-controller
  labels:
    app: spark
    component: spark-driver-ui-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-driver-ui-proxy
  template:
    metadata:
      labels:
        app: spark
        component: spark-driver-ui-proxy
    spec:
      containers:
      - name: spark-ui-proxy
        image: elsonrodriguez/spark-ui-proxy:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
        args:
        - spark-driver:8080
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-ui-proxy-lb
  labels:
    app: spark
    component: spark-driver-ui-proxy
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: spark-driver-ui-proxy
  type: LoadBalancer
